// src/components/CodeBlock.tsx
import React, { useCallback } from 'react'

export interface CodeBlockProps {
  code: string
  language?: string
  copyable?: boolean
}

export function CodeBlock({ code, language, copyable = false }: CodeBlockProps) {
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code)
  }, [code])

  return (
    <div data-ra-code-block="" data-ra-language={language}>
      <pre>
        <code>{code}</code>
      </pre>
      {copyable && (
        <button onClick={handleCopy} data-ra-copy="" type="button">
          Copy
        </button>
      )}
    </div>
  )
}

// packages/svelte/src/components/CodeBlock.svelte
<script lang="ts">
  let {
    code,
    language,
    copyable = false,
  }: { code: string; language?: string; copyable?: boolean } = $props()

  function copy() {
    void globalThis.navigator?.clipboard?.writeText(code)
  }
</script>

<div data-ak-code-block data-ak-language={language}>
  <pre><code>{code}</code></pre>
  {#if copyable}
    <button data-ak-copy type="button" onclick={copy}>Copy</button>
  {/if}
</div>
