// packages/react-native/src/components.tsx
import React, { useCallback, useEffect, useRef, useState, type ReactNode } from 'react'
import { Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import type { Message as MessageType, ChatReturn, ToolCall } from '@agentskit/core'

/**
 * Headless React Native chat components — RN-primitive mirror of the
 * `@agentskit/react` headless contract.
 *
 * React Native has no DOM, so there are no `data-ak-*` attributes. The
 * web-parity story is carried by `testID` props (`ak-message`, `ak-input`,
 * etc.): the same stable hooks AI-generated UIs and tests target on the web,
 * surfaced through RN's native `testID` (Appium / e2e) instead. Role and
 * status are conveyed via `accessibilityLabel`. No `StyleSheet`/colors are
 * hardcoded — consumers style through the optional `style` pass-through where
 * a host primitive accepts it.
 */

// Minimal structural style type — avoids depending on react-native's
// StyleProp/ViewStyle types at the surface (kept peer/external).
type Style = Record<string, unknown> | Array<Record<string, unknown>> | undefined

// ---------------------------------------------------------------------------
// ChatContainer — ScrollView wrapper + children + auto-scroll to end.
// ---------------------------------------------------------------------------

export interface ChatContainerProps {
  children: ReactNode
  style?: Style
  testID?: string
}

export function ChatContainer({ children, style, testID = 'ak-chat-container' }: ChatContainerProps) {
  const scrollRef = useRef<ScrollView>(null)

  const scrollToEnd = useCallback(() => {
    scrollRef.current?.scrollToEnd?.({ animated: true })
  }, [])

  useEffect(() => {
    scrollToEnd()
  }, [children, scrollToEnd])

  return (
    <ScrollView
      ref={scrollRef}
      testID={testID}
      style={style}
      onContentSizeChange={scrollToEnd}
    >
      {children}
    </ScrollView>
  )
}

// ---------------------------------------------------------------------------
// Message — message prop -> View + Text. Role/status via accessibilityLabel.
// ---------------------------------------------------------------------------

export interface MessageProps {
  message: MessageType
  avatar?: ReactNode
  actions?: ReactNode
  style?: Style
  testID?: string
}

export function Message({ message, avatar, actions, style, testID = 'ak-message' }: MessageProps) {
  return (
    <View
      testID={testID}
      style={style}
      accessibilityLabel={`${message.role} message (${message.status})`}
    >
      {avatar ? <View testID="ak-avatar">{avatar}</View> : null}
      <Text testID="ak-content">{message.content}</Text>
      {actions ? <View testID="ak-actions">{actions}</View> : null}
    </View>
  )
}

// ---------------------------------------------------------------------------
// InputBar — ChatReturn -> TextInput + Pressable "Send".
// onSubmitEditing sends; disabled when empty or streaming.
// ---------------------------------------------------------------------------

export interface InputBarProps {
  chat: ChatReturn
  placeholder?: string
  disabled?: boolean
  style?: Style
  testID?: string
}

export function InputBar({
  chat,
  placeholder = 'Type a message...',
  disabled = false,
  style,
  testID = 'ak-input-bar',
}: InputBarProps) {
  const isStreaming = chat.status === 'streaming'
  const canSend = !disabled && !isStreaming && chat.input.trim().length > 0

  const handleSend = useCallback(() => {
    if (chat.input.trim()) {
      chat.send(chat.input)
    }
  }, [chat])

  return (
    <View testID={testID} style={style}>
      <TextInput
        testID="ak-input"
        value={chat.input}
        onChangeText={chat.setInput}
        onSubmitEditing={handleSend}
        placeholder={placeholder}
        editable={!disabled && !isStreaming}
        accessibilityLabel="Message input"
      />
      <Pressable
        testID="ak-send"
        onPress={handleSend}
        disabled={!canSend}
        accessibilityRole="button"
        accessibilityLabel="Send message"
        accessibilityState={{ disabled: !canSend }}
      >
        <Text>Send</Text>
      </Pressable>
    </View>
  )
}

// ---------------------------------------------------------------------------
// Markdown — content + streaming -> Text (no DOM renderer on RN).
// ---------------------------------------------------------------------------

export interface MarkdownProps {
  content: string
  streaming?: boolean
  style?: Style
  testID?: string
}

export function Markdown({ content, streaming = false, style, testID = 'ak-markdown' }: MarkdownProps) {
  return (
    <Text
      testID={testID}
      style={style}
      accessibilityLabel={streaming ? 'streaming markdown' : 'markdown'}
    >
      {content}
    </Text>
  )
}

// ---------------------------------------------------------------------------
// CodeBlock — code + language + copyable -> View + Text + optional copy.
// ---------------------------------------------------------------------------

export interface CodeBlockProps {
  code: string
  language?: string
  copyable?: boolean
  onCopy?: (code: string) => void
  style?: Style
  testID?: string
}

export function CodeBlock({
  code,
  language,
  copyable = false,
  onCopy,
  style,
  testID = 'ak-code-block',
}: CodeBlockProps) {
  const handleCopy = useCallback(() => {
    onCopy?.(code)
  }, [onCopy, code])

  return (
    <View
      testID={testID}
      style={style}
      accessibilityLabel={language ? `code block (${language})` : 'code block'}
    >
      <Text testID="ak-code">{code}</Text>
      {copyable ? (
        <Pressable
          testID="ak-copy"
          onPress={handleCopy}
          accessibilityRole="button"
          accessibilityLabel="Copy code"
        >
          <Text>Copy</Text>
        </Pressable>
      ) : null}
    </View>
  )
}

// ---------------------------------------------------------------------------
// ToolCallView — toolCall; useState expanded; Pressable toggle.
// ---------------------------------------------------------------------------

export interface ToolCallViewProps {
  toolCall: ToolCall
  style?: Style
  testID?: string
}

export function ToolCallView({ toolCall, style, testID = 'ak-tool-call' }: ToolCallViewProps) {
  const [expanded, setExpanded] = useState(false)

  return (
    <View
      testID={testID}
      style={style}
      accessibilityLabel={`tool ${toolCall.name} (${toolCall.status})`}
    >
      <Pressable
        testID="ak-tool-toggle"
        onPress={() => setExpanded(prev => !prev)}
        accessibilityRole="button"
        accessibilityState={{ expanded }}
      >
        <Text>{toolCall.name}</Text>
      </Pressable>
      {expanded ? (
        <View testID="ak-tool-details">
          <Text testID="ak-tool-args">{JSON.stringify(toolCall.args, null, 2)}</Text>
          {toolCall.result ? <Text testID="ak-tool-result">{toolCall.result}</Text> : null}
        </View>
      ) : null}
    </View>
  )
}

// ---------------------------------------------------------------------------
// ThinkingIndicator — visible + label -> null when !visible.
// ---------------------------------------------------------------------------

export interface ThinkingIndicatorProps {
  visible: boolean
  label?: string
  style?: Style
  testID?: string
}

export function ThinkingIndicator({
  visible,
  label = 'Thinking...',
  style,
  testID = 'ak-thinking',
}: ThinkingIndicatorProps) {
  if (!visible) return null

  return (
    <View testID={testID} style={style} accessibilityLabel={label}>
      <Text testID="ak-thinking-label">{label}</Text>
    </View>
  )
}

// ---------------------------------------------------------------------------
// ToolConfirmation — toolCall + onApprove + onDeny.
// null unless status === 'requires_confirmation'.
// ---------------------------------------------------------------------------

export interface ToolConfirmationProps {
  toolCall: ToolCall
  onApprove: (toolCallId: string) => void
  onDeny: (toolCallId: string, reason?: string) => void
  style?: Style
  testID?: string
}

export function ToolConfirmation({
  toolCall,
  onApprove,
  onDeny,
  style,
  testID = 'ak-tool-confirmation',
}: ToolConfirmationProps) {
  if (toolCall.status !== 'requires_confirmation') return null

  return (
    <View
      testID={testID}
      style={style}
      accessibilityLabel={`${toolCall.name} requires confirmation`}
    >
      <View testID="ak-tool-confirmation-header">
        <Text testID="ak-tool-confirmation-name">{toolCall.name}</Text>
        <Text testID="ak-tool-confirmation-status">requires confirmation</Text>
      </View>
      <Text testID="ak-tool-confirmation-args">{JSON.stringify(toolCall.args, null, 2)}</Text>
      <View testID="ak-tool-confirmation-actions">
        <Pressable
          testID="ak-tool-confirmation-approve"
          onPress={() => onApprove(toolCall.id)}
          accessibilityRole="button"
          accessibilityLabel="Approve tool call"
        >
          <Text>Approve</Text>
        </Pressable>
        <Pressable
          testID="ak-tool-confirmation-deny"
          onPress={() => onDeny(toolCall.id)}
          accessibilityRole="button"
          accessibilityLabel="Deny tool call"
        >
          <Text>Deny</Text>
        </Pressable>
      </View>
    </View>
  )
}

// packages/angular/src/components.ts
import {
  Component,
  Input,
  ViewChild,
  ElementRef,
  signal,
  type AfterViewInit,
  type OnDestroy,
} from '@angular/core'
import type { Message as MessageType, ChatReturn, ToolCall } from '@agentskit/core'

/**
 * Headless Angular chat components mirroring `@agentskit/react`'s set. Each
 * renders `data-ak-*` attributes only — bring your own CSS. Standalone with
 * inline templates; published as partial-Ivy (AOT/APF) via ng-packagr.
 */

@Component({
  selector: 'ak-chat-container',
  standalone: true,
  template: `<div #scroll data-ak-chat-container data-testid="ak-chat-container"><ng-content /></div>`,
})
export class ChatContainerComponent implements AfterViewInit, OnDestroy {
  @ViewChild('scroll', { static: true }) scrollRef!: ElementRef<HTMLDivElement>
  private observer?: MutationObserver

  ngAfterViewInit(): void {
    const el = this.scrollRef?.nativeElement
    if (!el || typeof MutationObserver === 'undefined') return
    const observer = new MutationObserver(() => {
      el.scrollTop = el.scrollHeight
    })
    // Some non-browser envs (e.g. happy-dom) expose a partial MutationObserver.
    if (typeof observer.observe !== 'function') return
    this.observer = observer
    observer.observe(el, { childList: true, subtree: true, characterData: true })
  }

  ngOnDestroy(): void {
    if (typeof this.observer?.disconnect === 'function') this.observer.disconnect()
  }
}

@Component({
  selector: 'ak-message',
  standalone: true,
  template: `<div
    data-ak-message
    [attr.data-ak-role]="message.role"
    [attr.data-ak-status]="message.status"
  >
    <div data-ak-content>{{ message.content }}</div>
  </div>`,
})
export class MessageComponent {
  @Input({ required: true }) message!: MessageType
}

@Component({
  selector: 'ak-input-bar',
  standalone: true,
  template: `<form data-ak-input-bar (submit)="onSubmit($event)">
    <textarea
      data-ak-input
      rows="1"
      [value]="chat.input"
      [attr.placeholder]="placeholder"
      [disabled]="isBlocked"
      (input)="chat.setInput($any($event.target).value)"
      (keydown.enter)="onEnter($event)"
    ></textarea>
    <button data-ak-send type="submit" [disabled]="isBlocked || !chat.input.trim()">Send</button>
  </form>`,
})
export class InputBarComponent {
  @Input({ required: true }) chat!: ChatReturn
  @Input() placeholder = 'Type a message...'
  @Input() disabled = false

  get isBlocked(): boolean {
    return this.disabled || this.chat.status === 'streaming'
  }

  onSubmit(e: Event): void {
    e.preventDefault()
    this.submit()
  }

  onEnter(e: Event): void {
    if (!(e as KeyboardEvent).shiftKey) {
      e.preventDefault()
      this.submit()
    }
  }

  private submit(): void {
    if (this.isBlocked || !this.chat.input.trim()) return
    void this.chat.send(this.chat.input)
  }
}

@Component({
  selector: 'ak-markdown',
  standalone: true,
  template: `<div data-ak-markdown [attr.data-ak-streaming]="streaming ? 'true' : null">{{ content }}</div>`,
})
export class MarkdownComponent {
  @Input({ required: true }) content = ''
  @Input() streaming = false
}

@Component({
  selector: 'ak-code-block',
  standalone: true,
  template: `<div data-ak-code-block [attr.data-ak-language]="language">
    <pre><code>{{ code }}</code></pre>
    @if (copyable) {
      <button data-ak-copy type="button" (click)="copy()">Copy</button>
    }
  </div>`,
})
export class CodeBlockComponent {
  @Input({ required: true }) code = ''
  @Input() language?: string
  @Input() copyable = false

  copy(): void {
    void globalThis.navigator?.clipboard?.writeText(this.code)
  }
}

@Component({
  selector: 'ak-tool-call-view',
  standalone: true,
  template: `<div data-ak-tool-call [attr.data-ak-tool-status]="toolCall.status">
    <button
      data-ak-tool-toggle
      type="button"
      [attr.aria-expanded]="expanded()"
      (click)="expanded.set(!expanded())"
    >
      {{ toolCall.name }}
    </button>
    @if (expanded()) {
      <div data-ak-tool-details>
        <pre data-ak-tool-args>{{ argsJson }}</pre>
        @if (toolCall.result) {
          <div data-ak-tool-result>{{ toolCall.result }}</div>
        }
      </div>
    }
  </div>`,
})
export class ToolCallViewComponent {
  @Input({ required: true }) toolCall!: ToolCall
  readonly expanded = signal(false)

  get argsJson(): string {
    return JSON.stringify(this.toolCall.args, null, 2)
  }
}

@Component({
  selector: 'ak-thinking-indicator',
  standalone: true,
  template: `@if (visible) {
    <div data-ak-thinking>
      <span data-ak-thinking-dots><span>•</span><span>•</span><span>•</span></span>
      <span data-ak-thinking-label>{{ label }}</span>
    </div>
  }`,
})
export class ThinkingIndicatorComponent {
  @Input({ required: true }) visible = false
  @Input() label = 'Thinking...'
}

@Component({
  selector: 'ak-tool-confirmation',
  standalone: true,
  template: `@if (toolCall.status === 'requires_confirmation') {
    <div data-ak-tool-confirmation [attr.data-ak-tool-name]="toolCall.name">
      <div data-ak-tool-confirmation-header>
        <span data-ak-tool-confirmation-name>{{ toolCall.name }}</span>
        <span data-ak-tool-confirmation-status>requires confirmation</span>
      </div>
      <div data-ak-tool-confirmation-args>{{ argsJson }}</div>
      <div data-ak-tool-confirmation-actions>
        <button data-ak-tool-confirmation-approve type="button" (click)="onApprove(toolCall.id)">
          Approve
        </button>
        <button data-ak-tool-confirmation-deny type="button" (click)="onDeny(toolCall.id)">
          Deny
        </button>
      </div>
    </div>
  }`,
})
export class ToolConfirmationComponent {
  @Input({ required: true }) toolCall!: ToolCall
  @Input({ required: true }) onApprove!: (toolCallId: string) => void
  @Input({ required: true }) onDeny!: (toolCallId: string, reason?: string) => void

  get argsJson(): string {
    return JSON.stringify(this.toolCall.args, null, 2)
  }
}
