// packages/svelte/src/components/ToolCallView.svelte
<script lang="ts">
  import type { ToolCall } from '@agentskit/core'

  let { toolCall }: { toolCall: ToolCall } = $props()
  let expanded = $state(false)
</script>

<div data-ak-tool-call data-ak-tool-status={toolCall.status}>
  <button
    data-ak-tool-toggle
    type="button"
    aria-expanded={expanded}
    onclick={() => (expanded = !expanded)}
  >
    {toolCall.name}
  </button>
  {#if expanded}
    <div data-ak-tool-details>
      <pre data-ak-tool-args>{JSON.stringify(toolCall.args, null, 2)}</pre>
      {#if toolCall.result}<div data-ak-tool-result>{toolCall.result}</div>{/if}
    </div>
  {/if}
</div>

// packages/react/src/components/ToolCallView.tsx
import React, { useState } from 'react'
import type { ToolCall } from '@agentskit/core'

export interface ToolCallViewProps {
  toolCall: ToolCall
}

export function ToolCallView({ toolCall }: ToolCallViewProps) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div data-ak-tool-call="" data-ak-tool-status={toolCall.status}>
      <button
        onClick={() => setExpanded(!expanded)}
        data-ak-tool-toggle=""
        type="button"
        aria-expanded={expanded}
      >
        {toolCall.name}
      </button>
      {expanded && (
        <div data-ak-tool-details="">
          <pre data-ak-tool-args="">
            {JSON.stringify(toolCall.args, null, 2)}
          </pre>
          {toolCall.result && (
            <div data-ak-tool-result="">{toolCall.result}</div>
          )}
        </div>
      )}
    </div>
  )
}
