// packages/react/src/components/ChatContainer.tsx
import React, { useRef, useEffect, type ReactNode } from 'react'

/** Props for a chat region that scrolls as its rendered content changes. */
export interface ChatContainerProps {
  children: ReactNode
  className?: string
}

/**
 * Render chat children in a container that scrolls to new content.
 * @param props The container children and optional class name.
 * @returns The chat container element.
 * @example
 * ```tsx
 * <ChatContainer>{messages.map(message => <Message key={message.id} message={message} />)}</ChatContainer>
 * ```
 */
export function ChatContainer({ children, className }: ChatContainerProps) {
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const el = containerRef.current
    if (!el) return

    const observer = new MutationObserver(() => {
      el.scrollTop = el.scrollHeight
    })

    observer.observe(el, { childList: true, subtree: true, characterData: true })
    return () => observer.disconnect()
  }, [])

  return (
    <div
      ref={containerRef}
      data-ak-chat-container=""
      data-testid="ak-chat-container"
      className={className}
    >
      {children}
    </div>
  )
}

// packages/solid/src/components/ChatContainer.tsx
import { onMount, onCleanup, type JSX } from 'solid-js'

/** Props accepted by the reactive chat scroll container. */
export interface ChatContainerProps {
  children?: JSX.Element
  class?: string
}

/** Render a scroll container that follows newly added chat content.
 * @param props Container children and optional CSS class.
 * @returns The headless chat container element.
 */
export function ChatContainer(props: ChatContainerProps): JSX.Element {
  let containerRef: HTMLDivElement | undefined

  onMount(() => {
    const el = containerRef
    if (!el) return

    const observer = new MutationObserver(() => {
      el.scrollTop = el.scrollHeight
    })

    observer.observe(el, { childList: true, subtree: true, characterData: true })
    onCleanup(() => observer.disconnect())
  })

  return (
    <div
      ref={(el) => (containerRef = el)}
      data-ak-chat-container=""
      data-testid="ak-chat-container"
      class={props.class}
    >
      {props.children}
    </div>
  )
}
