// src/components/CodeBlock.tsx
import React, { useCallback } from 'react'

export interface CodeBlockProps {
  code: string
  language?: string
  copyable?: boolean
}

export function CodeBlock({ code, language, copyable = false }: CodeBlockProps) {
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code)
  }, [code])

  return (
    <div data-ra-code-block="" data-ra-language={language}>
      <pre>
        <code>{code}</code>
      </pre>
      {copyable && (
        <button onClick={handleCopy} data-ra-copy="" type="button">
          Copy
        </button>
      )}
    </div>
  )
}

// packages/solid/src/components/CodeBlock.tsx
import { Show, type JSX } from 'solid-js'

export interface CodeBlockProps {
  code: string
  language?: string
  copyable?: boolean
}

export function CodeBlock(props: CodeBlockProps): JSX.Element {
  const handleCopy = () => {
    navigator.clipboard.writeText(props.code)
  }

  return (
    <div data-ak-code-block="" data-ak-language={props.language}>
      <pre>
        <code>{props.code}</code>
      </pre>
      <Show when={props.copyable}>
        <button onClick={handleCopy} data-ak-copy="" type="button">
          Copy
        </button>
      </Show>
    </div>
  )
}
