// packages/svelte/src/components/InputBar.svelte
<script lang="ts">
  import type { ChatReturn } from '@agentskit/core'

  let {
    chat,
    placeholder = 'Type a message...',
    disabled = false,
  }: { chat: ChatReturn; placeholder?: string; disabled?: boolean } = $props()

  function submit() {
    if (chat.input.trim()) chat.send(chat.input)
  }
</script>

<form
  data-ak-input-bar
  onsubmit={(e) => {
    e.preventDefault()
    submit()
  }}
>
  <textarea
    role="textbox"
    data-ak-input
    rows="1"
    {placeholder}
    {disabled}
    value={chat.input}
    oninput={(e) => chat.setInput(e.currentTarget.value)}
    onkeydown={(e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        submit()
      }
    }}
  ></textarea>
  <button data-ak-send type="submit" disabled={disabled || !chat.input.trim()}>Send</button>
</form>

// packages/solid/src/components/InputBar.tsx
import { type JSX } from 'solid-js'
import type { ChatReturn } from '@agentskit/core'

export interface InputBarProps {
  chat: ChatReturn
  placeholder?: string
  disabled?: boolean
}

export function InputBar(props: InputBarProps): JSX.Element {
  const placeholder = () => props.placeholder ?? 'Type a message...'
  const disabled = () => props.disabled ?? false

  const handleSubmit = (e: Event) => {
    e.preventDefault()
    if (props.chat.input.trim()) {
      props.chat.send(props.chat.input)
    }
  }

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      if (props.chat.input.trim()) {
        props.chat.send(props.chat.input)
      }
    }
  }

  return (
    <form data-ak-input-bar="" onSubmit={handleSubmit}>
      <textarea
        role="textbox"
        value={props.chat.input}
        onInput={(e) => props.chat.setInput(e.currentTarget.value)}
        onKeyDown={handleKeyDown}
        placeholder={placeholder()}
        disabled={disabled()}
        data-ak-input=""
        rows={1}
      />
      <button
        type="submit"
        disabled={disabled() || !props.chat.input.trim()}
        data-ak-send=""
      >
        Send
      </button>
    </form>
  )
}
