// packages/react/src/components/Markdown.tsx
import React from 'react'

/** Props for displaying message content with a streaming marker. */
export interface MarkdownProps {
  content: string
  streaming?: boolean
}

/**
 * Display content as text and mark it while the response is streaming.
 * @param props The content and optional streaming state.
 * @returns The marked content element.
 */
export function Markdown({ content, streaming = false }: MarkdownProps) {
  return (
    <div data-ak-markdown="" data-ak-streaming={streaming ? 'true' : undefined}>
      {content}
    </div>
  )
}

// packages/solid/src/components/Markdown.tsx
import { type JSX } from 'solid-js'

/** Props accepted by the markdown content surface. */
export interface MarkdownProps {
  content: string
  streaming?: boolean
}

/** Render text content with an optional streaming data attribute.
 * @param props The content and optional streaming state.
 * @returns The headless markdown element.
 */
export function Markdown(props: MarkdownProps): JSX.Element {
  return (
    <div data-ak-markdown="" data-ak-streaming={props.streaming ? 'true' : undefined}>
      {props.content}
    </div>
  )
}
