// packages/react/src/components/ThinkingIndicator.tsx
import React from 'react'

/** Props for showing a labeled thinking indicator. */
export interface ThinkingIndicatorProps {
  visible: boolean
  label?: string
}

/**
 * Render a thinking indicator when `visible` is true.
 * @param props The visibility flag and optional label.
 * @returns The indicator element or `null`.
 */
export function ThinkingIndicator({ visible, label = 'Thinking...' }: ThinkingIndicatorProps) {
  if (!visible) return null

  return (
    <div data-ak-thinking="" data-testid="ak-thinking">
      <span data-ak-thinking-dots="">
        <span>&bull;</span><span>&bull;</span><span>&bull;</span>
      </span>
      <span data-ak-thinking-label="">{label}</span>
    </div>
  )
}

// packages/solid/src/components/ThinkingIndicator.tsx
import { Show, type JSX } from 'solid-js'

/** Props accepted by the conditional thinking status display. */
export interface ThinkingIndicatorProps {
  visible: boolean
  label?: string
}

/** Render a status indicator only while the chat is waiting.
 * @param props Visibility and optional label settings.
 * @returns The thinking indicator element or an empty value.
 */
export function ThinkingIndicator(props: ThinkingIndicatorProps): JSX.Element {
  const label = () => props.label ?? 'Thinking...'

  return (
    <Show when={props.visible}>
      <div data-ak-thinking="" data-testid="ak-thinking">
        <span data-ak-thinking-dots="">
          <span>&bull;</span>
          <span>&bull;</span>
          <span>&bull;</span>
        </span>
        <span data-ak-thinking-label="">{label()}</span>
      </div>
    </Show>
  )
}
