// packages/react/src/components/ToolCallView.tsx
import React, { useState } from 'react'
import type { ToolCall } from '@agentskit/core'

export interface ToolCallViewProps {
  toolCall: ToolCall
}

export function ToolCallView({ toolCall }: ToolCallViewProps) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div data-ak-tool-call="" data-ak-tool-status={toolCall.status}>
      <button
        onClick={() => setExpanded(!expanded)}
        data-ak-tool-toggle=""
        type="button"
        aria-expanded={expanded}
      >
        {toolCall.name}
      </button>
      {expanded && (
        <div data-ak-tool-details="">
          <pre data-ak-tool-args="">
            {JSON.stringify(toolCall.args, null, 2)}
          </pre>
          {toolCall.result && (
            <div data-ak-tool-result="">{toolCall.result}</div>
          )}
        </div>
      )}
    </div>
  )
}

// packages/solid/src/components/ToolCallView.tsx
import { createSignal, Show, type JSX } from 'solid-js'
import type { ToolCall } from '@agentskit/core'

export interface ToolCallViewProps {
  toolCall: ToolCall
}

export function ToolCallView(props: ToolCallViewProps): JSX.Element {
  const [expanded, setExpanded] = createSignal(false)

  return (
    <div data-ak-tool-call="" data-ak-tool-status={props.toolCall.status}>
      <button
        onClick={() => setExpanded(!expanded())}
        data-ak-tool-toggle=""
        type="button"
        aria-expanded={expanded()}
      >
        {props.toolCall.name}
      </button>
      <Show when={expanded()}>
        <div data-ak-tool-details="">
          <pre data-ak-tool-args="">
            {JSON.stringify(props.toolCall.args, null, 2)}
          </pre>
          <Show when={props.toolCall.result}>
            <div data-ak-tool-result="">{props.toolCall.result}</div>
          </Show>
        </div>
      </Show>
    </div>
  )
}
