// packages/solid/src/components/Markdown.tsx
import { type JSX } from 'solid-js'

export interface MarkdownProps {
  content: string
  streaming?: boolean
}

export function Markdown(props: MarkdownProps): JSX.Element {
  return (
    <div data-ak-markdown="" data-ak-streaming={props.streaming ? 'true' : undefined}>
      {props.content}
    </div>
  )
}

// src/components/Markdown.tsx
import React from 'react'

export interface MarkdownProps {
  content: string
  streaming?: boolean
}

export function Markdown({ content, streaming = false }: MarkdownProps) {
  return (
    <div data-ra-markdown="" data-ra-streaming={streaming ? 'true' : undefined}>
      {content}
    </div>
  )
}
