// packages/solid/src/components/ThinkingIndicator.tsx
import { Show, type JSX } from 'solid-js'

export interface ThinkingIndicatorProps {
  visible: boolean
  label?: string
}

export function ThinkingIndicator(props: ThinkingIndicatorProps): JSX.Element {
  const label = () => props.label ?? 'Thinking...'

  return (
    <Show when={props.visible}>
      <div data-ak-thinking="" data-testid="ak-thinking">
        <span data-ak-thinking-dots="">
          <span>&bull;</span>
          <span>&bull;</span>
          <span>&bull;</span>
        </span>
        <span data-ak-thinking-label="">{label()}</span>
      </div>
    </Show>
  )
}

// src/components/ThinkingIndicator.tsx
import React from 'react'

export interface ThinkingIndicatorProps {
  visible: boolean
  label?: string
}

export function ThinkingIndicator({ visible, label = 'Thinking...' }: ThinkingIndicatorProps) {
  if (!visible) return null

  return (
    <div data-ra-thinking="" data-testid="ra-thinking">
      <span data-ra-thinking-dots="">
        <span>&bull;</span><span>&bull;</span><span>&bull;</span>
      </span>
      <span data-ra-thinking-label="">{label}</span>
    </div>
  )
}
